# Generated by Django 3.1.7 on 2021-03-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210327_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_desc',
            field=models.CharField(default='no description', max_length=500),
        ),
    ]
